import type { PersonaId } from "@/lib/personas";

export type PersonaVoiceConfig = {
  elevenLabsVoiceId?: string;
  elevenLabsStability?: number;
  elevenLabsSimilarityBoost?: number;
  elevenLabsStyle?: number;
  elevenLabsSpeakerBoost?: boolean;
  piperModel: string;
  piperSpeaker?: number;
  piperLengthScale?: number;
  piperNoiseScale?: number;
  piperNoiseWScale?: number;
  piperSentenceSilence?: number;
  xttsSpeakerId?: string;
  xttsSpeakerWav?: string;
  xttsLanguage: string;
  browserVoiceHint: string;
  browserRate: number;
  browserPitch: number;
};

export const PERSONA_VOICE_MAP: Record<PersonaId, PersonaVoiceConfig> = {
  mlk: {
    elevenLabsVoiceId: process.env.ELEVENLABS_VOICE_MLK ?? "ErXwobaYiN019PkySvjV",
    elevenLabsStability: 0.86,
    elevenLabsSimilarityBoost: 0.86,
    elevenLabsStyle: 0.1,
    elevenLabsSpeakerBoost: true,
    piperModel: "en_US-john-medium.onnx",
    piperLengthScale: 1.06,
    piperNoiseScale: 0.48,
    piperNoiseWScale: 0.62,
    piperSentenceSilence: 0.3,
    xttsSpeakerId: "Torcull Diarmuid",
    xttsLanguage: "en",
    browserVoiceHint: "Alex",
    browserRate: 0.9,
    browserPitch: 0.75,
  },
  rosa: {
    elevenLabsVoiceId: process.env.ELEVENLABS_VOICE_ROSA ?? "21m00Tcm4TlvDq8ikWAM",
    elevenLabsStability: 0.8,
    elevenLabsSimilarityBoost: 0.84,
    elevenLabsStyle: 0.1,
    elevenLabsSpeakerBoost: true,
    piperModel: "en_US-amy-medium.onnx",
    piperLengthScale: 1.03,
    piperNoiseScale: 0.5,
    piperNoiseWScale: 0.64,
    piperSentenceSilence: 0.24,
    xttsSpeakerId: "Camilla Holmström",
    xttsLanguage: "en",
    browserVoiceHint: "Samantha",
    browserRate: 0.92,
    browserPitch: 0.92,
  },
  malcolmx: {
    elevenLabsVoiceId: process.env.ELEVENLABS_VOICE_MALCOLMX ?? "VR6AewLTigWG4xSOukaG",
    elevenLabsStability: 0.74,
    elevenLabsSimilarityBoost: 0.84,
    elevenLabsStyle: 0.2,
    elevenLabsSpeakerBoost: true,
    piperModel: "en_US-ryan-high.onnx",
    piperLengthScale: 0.98,
    piperNoiseScale: 0.52,
    piperNoiseWScale: 0.66,
    piperSentenceSilence: 0.2,
    xttsSpeakerId: "Damien Black",
    xttsLanguage: "en",
    browserVoiceHint: "Daniel",
    browserRate: 0.95,
    browserPitch: 0.8,
  },
  douglass: {
    elevenLabsVoiceId: process.env.ELEVENLABS_VOICE_DOUGLASS ?? "TxGEqnHWrfWFTfGW9XjX",
    elevenLabsStability: 0.82,
    elevenLabsSimilarityBoost: 0.86,
    elevenLabsStyle: 0.08,
    elevenLabsSpeakerBoost: true,
    piperModel: "en_US-john-medium.onnx",
    piperLengthScale: 1.1,
    piperNoiseScale: 0.48,
    piperNoiseWScale: 0.62,
    piperSentenceSilence: 0.28,
    xttsSpeakerId: "Viktor Menelaos",
    xttsLanguage: "en",
    browserVoiceHint: "Alex",
    browserRate: 0.88,
    browserPitch: 0.72,
  },
  tubman: {
    elevenLabsVoiceId: process.env.ELEVENLABS_VOICE_TUBMAN ?? "TxGEqnHWrfWFTfGW9XjX",
    elevenLabsStability: 0.84,
    elevenLabsSimilarityBoost: 0.86,
    elevenLabsStyle: 0.08,
    elevenLabsSpeakerBoost: true,
    piperModel: "en_US-john-medium.onnx",
    piperLengthScale: 1.08,
    piperNoiseScale: 0.48,
    piperNoiseWScale: 0.62,
    piperSentenceSilence: 0.28,
    xttsSpeakerId: "Viktor Menelaos",
    xttsLanguage: "en",
    browserVoiceHint: "Alex",
    browserRate: 0.9,
    browserPitch: 0.74,
  },
  dubois: {
    elevenLabsVoiceId: process.env.ELEVENLABS_VOICE_DUBOIS ?? "ErXwobaYiN019PkySvjV",
    elevenLabsStability: 0.86,
    elevenLabsSimilarityBoost: 0.88,
    elevenLabsStyle: 0.08,
    elevenLabsSpeakerBoost: true,
    piperModel: "en_US-john-medium.onnx",
    piperLengthScale: 1.08,
    piperNoiseScale: 0.48,
    piperNoiseWScale: 0.62,
    piperSentenceSilence: 0.28,
    xttsSpeakerId: "Torcull Diarmuid",
    xttsLanguage: "en",
    browserVoiceHint: "Alex",
    browserRate: 0.88,
    browserPitch: 0.72,
  },
  marshall: {
    elevenLabsVoiceId: process.env.ELEVENLABS_VOICE_MARSHALL ?? "VR6AewLTigWG4xSOukaG",
    elevenLabsStability: 0.8,
    elevenLabsSimilarityBoost: 0.84,
    elevenLabsStyle: 0.1,
    elevenLabsSpeakerBoost: true,
    piperModel: "en_US-ryan-high.onnx",
    piperLengthScale: 1.0,
    piperNoiseScale: 0.5,
    piperNoiseWScale: 0.64,
    piperSentenceSilence: 0.24,
    xttsSpeakerId: "Damien Black",
    xttsLanguage: "en",
    browserVoiceHint: "Daniel",
    browserRate: 0.93,
    browserPitch: 0.8,
  },
  katherinejohnson: {
    elevenLabsVoiceId: process.env.ELEVENLABS_VOICE_KATHERINEJOHNSON ?? "21m00Tcm4TlvDq8ikWAM",
    elevenLabsStability: 0.82,
    elevenLabsSimilarityBoost: 0.86,
    elevenLabsStyle: 0.1,
    elevenLabsSpeakerBoost: true,
    piperModel: "en_US-amy-medium.onnx",
    piperLengthScale: 1.0,
    piperNoiseScale: 0.5,
    piperNoiseWScale: 0.64,
    piperSentenceSilence: 0.22,
    xttsSpeakerId: "Camilla Holmström",
    xttsLanguage: "en",
    browserVoiceHint: "Samantha",
    browserRate: 0.94,
    browserPitch: 0.94,
  },
  newton: {
    elevenLabsVoiceId: process.env.ELEVENLABS_VOICE_NEWTON ?? "ErXwobaYiN019PkySvjV",
    elevenLabsStability: 0.84,
    elevenLabsSimilarityBoost: 0.86,
    elevenLabsStyle: 0.08,
    elevenLabsSpeakerBoost: true,
    piperModel: "en_US-john-medium.onnx",
    piperLengthScale: 1.1,
    piperNoiseScale: 0.48,
    piperNoiseWScale: 0.62,
    piperSentenceSilence: 0.3,
    xttsSpeakerId: "Ludvig Milivoj",
    xttsLanguage: "en",
    browserVoiceHint: "Alex",
    browserRate: 0.88,
    browserPitch: 0.72,
  },
  galileo: {
    elevenLabsVoiceId: process.env.ELEVENLABS_VOICE_GALILEO ?? "TxGEqnHWrfWFTfGW9XjX",
    elevenLabsStability: 0.74,
    elevenLabsSimilarityBoost: 0.82,
    elevenLabsStyle: 0.15,
    elevenLabsSpeakerBoost: true,
    piperModel: "en_US-ryan-high.onnx",
    piperLengthScale: 1.0,
    piperNoiseScale: 0.54,
    piperNoiseWScale: 0.66,
    piperSentenceSilence: 0.22,
    xttsSpeakerId: "Viktor Menelaos",
    xttsLanguage: "en",
    browserVoiceHint: "Daniel",
    browserRate: 0.95,
    browserPitch: 0.84,
  },
  curie: {
    elevenLabsVoiceId: process.env.ELEVENLABS_VOICE_CURIE ?? "21m00Tcm4TlvDq8ikWAM",
    elevenLabsStability: 0.8,
    elevenLabsSimilarityBoost: 0.86,
    elevenLabsStyle: 0.14,
    elevenLabsSpeakerBoost: true,
    piperModel: "en_US-amy-medium.onnx",
    piperLengthScale: 1.0,
    piperNoiseScale: 0.5,
    piperNoiseWScale: 0.64,
    piperSentenceSilence: 0.2,
    xttsSpeakerId: "Camilla Holmström",
    xttsLanguage: "en",
    browserVoiceHint: "Samantha",
    browserRate: 0.95,
    browserPitch: 0.96,
  },
  tesla: {
    elevenLabsVoiceId: process.env.ELEVENLABS_VOICE_TESLA ?? "VR6AewLTigWG4xSOukaG",
    elevenLabsStability: 0.68,
    elevenLabsSimilarityBoost: 0.82,
    elevenLabsStyle: 0.24,
    elevenLabsSpeakerBoost: true,
    piperModel: "en_GB-northern_english_male-medium.onnx",
    piperLengthScale: 1.0,
    piperNoiseScale: 0.58,
    piperNoiseWScale: 0.72,
    piperSentenceSilence: 0.22,
    xttsSpeakerId: "Damien Black",
    xttsLanguage: "en",
    browserVoiceHint: "Daniel",
    browserRate: 0.95,
    browserPitch: 0.82,
  },
  einstein: {
    elevenLabsVoiceId: process.env.ELEVENLABS_VOICE_EINSTEIN ?? "ErXwobaYiN019PkySvjV",
    elevenLabsStability: 0.82,
    elevenLabsSimilarityBoost: 0.88,
    elevenLabsStyle: 0.08,
    elevenLabsSpeakerBoost: true,
    piperModel: "en_US-john-medium.onnx",
    piperLengthScale: 1.14,
    piperNoiseScale: 0.48,
    piperNoiseWScale: 0.62,
    piperSentenceSilence: 0.3,
    xttsSpeakerId: "Ludvig Milivoj",
    xttsLanguage: "en",
    browserVoiceHint: "Daniel",
    browserRate: 0.86,
    browserPitch: 0.72,
  },
  jobs: {
    elevenLabsVoiceId: process.env.ELEVENLABS_VOICE_JOBS ?? "TxGEqnHWrfWFTfGW9XjX",
    elevenLabsStability: 0.44,
    elevenLabsSimilarityBoost: 0.83,
    elevenLabsStyle: 0.35,
    elevenLabsSpeakerBoost: true,
    piperModel: "en_US-ryan-high.onnx",
    piperLengthScale: 0.95,
    piperNoiseScale: 0.5,
    piperNoiseWScale: 0.65,
    piperSentenceSilence: 0.16,
    xttsSpeakerId: "Damien Black",
    xttsLanguage: "en",
    browserVoiceHint: "Google US English",
    browserRate: 1.02,
    browserPitch: 0.9,
  },
  napoleon: {
    elevenLabsVoiceId: process.env.ELEVENLABS_VOICE_NAPOLEON ?? "VR6AewLTigWG4xSOukaG",
    elevenLabsStability: 0.62,
    elevenLabsSimilarityBoost: 0.69,
    elevenLabsStyle: 0.25,
    elevenLabsSpeakerBoost: true,
    piperModel: "en_US-ryan-high.onnx",
    piperLengthScale: 0.98,
    piperNoiseScale: 0.58,
    piperNoiseWScale: 0.7,
    piperSentenceSilence: 0.18,
    xttsSpeakerId: "Zacharie Aimilios",
    xttsLanguage: "en",
    browserVoiceHint: "Alex",
    browserRate: 0.97,
    browserPitch: 0.82,
  },
  shakespeare: {
    elevenLabsVoiceId: process.env.ELEVENLABS_VOICE_SHAKESPEARE ?? "ErXwobaYiN019PkySvjV",
    elevenLabsStability: 0.66,
    elevenLabsSimilarityBoost: 0.78,
    elevenLabsStyle: 0.48,
    elevenLabsSpeakerBoost: true,
    piperModel: "en_GB-northern_english_male-medium.onnx",
    piperLengthScale: 1.1,
    piperNoiseScale: 0.64,
    piperNoiseWScale: 0.76,
    piperSentenceSilence: 0.28,
    xttsSpeakerId: "Torcull Diarmuid",
    xttsLanguage: "en",
    browserVoiceHint: "Daniel",
    browserRate: 0.92,
    browserPitch: 1.1,
  },
  companion: {
    elevenLabsVoiceId: process.env.ELEVENLABS_VOICE_COMPANION,
    elevenLabsStability: 0.7,
    elevenLabsSimilarityBoost: 0.7,
    elevenLabsStyle: 0.15,
    elevenLabsSpeakerBoost: true,
    piperModel: "en_US-libritts-high.onnx",
    piperLengthScale: 1.04,
    piperNoiseScale: 0.56,
    piperNoiseWScale: 0.7,
    piperSentenceSilence: 0.24,
    xttsLanguage: "en",
    browserVoiceHint: "Samantha",
    browserRate: 0.95,
    browserPitch: 1.02,
  },
};

export function getPersonaVoiceConfig(personaId: PersonaId): PersonaVoiceConfig {
  return PERSONA_VOICE_MAP[personaId] ?? PERSONA_VOICE_MAP.einstein;
}
